### ISSUE TITLE
riscalare legenda su periodi di cumulate oltre 24 ore

### ISSUE THREAD

**Issue by msalvati** [ARPASMR/lapris#1]
Se usato in modalità desktop per cumulare su piu' giorni le classi nella legenda risultano troppo basse: possibile soluzione moltiplicare il cvettore classi per un intero dipendente dal parametro n passato da linea di comando
ad es testare : floor((n-1)/24+1)

**Comment by mazanetti** [comment]
Aggiunti 2 nuovi colori per cumulate fino a 250mm.
Cambio legenda e raddoppio valori in caso di cumulate da 25 a 48 ore (oltre moltiplica per 3 fino a 72 ore etc etc etc)
Aggiustate dimensioni immagini per migliore risoluzione su web.
