### ISSUE TITLE
Trovare sistema per lanciare lo script R interattivamente da interfaccia grafica

### ISSUE THREAD

**Issue by msalvati** [ARPASMR/lapris#3]
E' possibile inserire un webserver sul container lapris con l'unica funzione dii far girare uno script php che lanci lo script R prendendo i parametri da un elenco/finestrella?

**Comment by mauromussin** [comment]
Attualmente c'è lo script recupero.sh che è dedicato a quello. L'unico difetto è che deve essere lanciato da una console del servizio. Per adesso chiudo l'issue e inserisco una richiesta per lanciare il recupero da interfaccia web tramite Flask (cosa che devo studiare meglio)
