### ISSUE TITLE
non si attiva in automatico dopo crash

### ISSUE THREAD

**Issue by mauromussin** [ARPASMR/lapris#8]
Il servizio nello swarm se viene rilanciato in automatico non esegue correttamente il ./launch_flash.sh che deve essere lanciato a mano

**Comment by eddiemi** [comment]
Bug risolto correggendo il nome dello script flask (launch_flask invece di launch_flash) nel launch.sh

**Comment by mauromussin** [comment]
________________________________
Da: eddiemi <notifications@github.com>
Inviato: sabato 21 novembre 2020 18:46
A: ARPASMR/lapris <lapris@noreply.github.com>
Cc: MUSSIN MAURO <M.MUSSIN@arpalombardia.it>; Author <author@noreply.github.com>
Oggetto: Re: [ARPASMR/lapris] non si attiva in automatico dopo crash (#8)


Bug risolto correggendo il nome dello script flask (launch_flask invece di launch_flash) nel launch.sh
